/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author Taka
 */
public class KalkulatorEa extends javax.swing.JFrame {
String angka = "";
double angka1, angka2, jumlah;
int pilih;

    /**
     * Creates new form KalkulatorEa
     */
    public KalkulatorEa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpil = new javax.swing.ButtonGroup();
        bil9 = new javax.swing.JButton();
        bil4 = new javax.swing.JButton();
        bil2 = new javax.swing.JButton();
        bil1 = new javax.swing.JButton();
        bil0 = new javax.swing.JButton();
        bil3 = new javax.swing.JButton();
        bil6 = new javax.swing.JButton();
        bil7 = new javax.swing.JButton();
        bil8 = new javax.swing.JButton();
        bil5 = new javax.swing.JButton();
        display = new javax.swing.JTextField();
        btnbagi = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        depanbtn = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnmin1 = new javax.swing.JButton();
        btnkoma = new javax.swing.JButton();
        btnpangkat = new javax.swing.JButton();
        btnpersen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setBackground(new java.awt.Color(255, 255, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        bil9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil9.setText("9");
        bil9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil9ActionPerformed(evt);
            }
        });
        getContentPane().add(bil9);
        bil9.setBounds(260, 200, 60, 40);

        bil4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil4.setText("4");
        bil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil4ActionPerformed(evt);
            }
        });
        getContentPane().add(bil4);
        bil4.setBounds(120, 250, 60, 40);

        bil2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil2.setText("2");
        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });
        getContentPane().add(bil2);
        bil2.setBounds(190, 300, 60, 40);

        bil1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil1.setText("1");
        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        getContentPane().add(bil1);
        bil1.setBounds(120, 300, 60, 40);

        bil0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil0.setText("0");
        bil0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil0ActionPerformed(evt);
            }
        });
        getContentPane().add(bil0);
        bil0.setBounds(120, 350, 130, 40);

        bil3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil3.setText("3");
        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });
        getContentPane().add(bil3);
        bil3.setBounds(260, 300, 60, 40);

        bil6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil6.setText("6");
        bil6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil6ActionPerformed(evt);
            }
        });
        getContentPane().add(bil6);
        bil6.setBounds(260, 250, 60, 40);

        bil7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil7.setText("7");
        bil7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil7ActionPerformed(evt);
            }
        });
        getContentPane().add(bil7);
        bil7.setBounds(120, 200, 60, 40);

        bil8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil8.setText("8");
        bil8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil8ActionPerformed(evt);
            }
        });
        getContentPane().add(bil8);
        bil8.setBounds(190, 200, 60, 40);

        bil5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bil5.setText("5");
        bil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil5ActionPerformed(evt);
            }
        });
        getContentPane().add(bil5);
        bil5.setBounds(190, 250, 60, 40);
        getContentPane().add(display);
        display.setBounds(40, 80, 350, 50);

        btnbagi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbagi.setText("/");
        btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnbagi);
        btnbagi.setBounds(330, 150, 60, 40);

        btnkali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkali.setText("x");
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkali);
        btnkali.setBounds(330, 200, 60, 40);

        btntambah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah);
        btntambah.setBounds(330, 250, 60, 40);

        depanbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depanbtn.setText("=");
        depanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depanbtnActionPerformed(evt);
            }
        });
        getContentPane().add(depanbtn);
        depanbtn.setBounds(330, 350, 60, 40);

        btnclear.setBackground(new java.awt.Color(0, 0, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 0));
        btnclear.setText("C");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(40, 150, 280, 40);

        btnmin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmin1.setText("-");
        btnmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnmin1);
        btnmin1.setBounds(330, 300, 60, 40);

        btnkoma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkoma.setText(".");
        btnkoma.setToolTipText("");
        btnkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnkoma);
        btnkoma.setBounds(260, 350, 60, 40);

        btnpangkat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpangkat.setText("^2");
        btnpangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpangkatActionPerformed(evt);
            }
        });
        getContentPane().add(btnpangkat);
        btnpangkat.setBounds(330, 400, 60, 40);

        btnpersen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpersen.setText("%");
        btnpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersenActionPerformed(evt);
            }
        });
        getContentPane().add(btnpersen);
        btnpersen.setBounds(260, 400, 60, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("MOD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 400, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Kalkulator EAa!!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 10, 310, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("KAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 400, 60, 40);

        btnsin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsin.setText("Sin");
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });
        getContentPane().add(btnsin);
        btnsin.setBounds(40, 200, 70, 40);

        btncos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncos.setText("Cos");
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });
        getContentPane().add(btncos);
        btncos.setBounds(40, 250, 70, 40);

        btntan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntan.setText("Tan");
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });
        getContentPane().add(btntan);
        btntan.setBounds(40, 300, 70, 40);

        btnlog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlog.setText("Log");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(40, 350, 70, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 470);

        setSize(new java.awt.Dimension(440, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bil0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil0ActionPerformed
     angka += "0";
     display.setText(angka);
    }//GEN-LAST:event_bil0ActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
     angka += "1";
     display.setText(angka);
    }//GEN-LAST:event_bil1ActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
     angka += "2";
     display.setText(angka);
    }//GEN-LAST:event_bil2ActionPerformed

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
     angka += "3";
     display.setText(angka);
    }//GEN-LAST:event_bil3ActionPerformed

    private void bil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil4ActionPerformed
     angka += "4";
     display.setText(angka);
    }//GEN-LAST:event_bil4ActionPerformed

    private void bil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil5ActionPerformed
     angka += "5";
     display.setText(angka);
    }//GEN-LAST:event_bil5ActionPerformed

    private void bil6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil6ActionPerformed
     angka += "6";
     display.setText(angka);
    }//GEN-LAST:event_bil6ActionPerformed

    private void bil7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil7ActionPerformed
     angka += "7";
     display.setText(angka);
    }//GEN-LAST:event_bil7ActionPerformed

    private void bil8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil8ActionPerformed
     angka += "8";
     display.setText(angka);
    }//GEN-LAST:event_bil8ActionPerformed

    private void bil9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil9ActionPerformed
     angka += "9";
     display.setText(angka);
    }//GEN-LAST:event_bil9ActionPerformed

    private void btnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("/");
        angka="";
        pilih=1;
    }//GEN-LAST:event_btnbagiActionPerformed

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("*");
        angka="";
        pilih=2;
    }//GEN-LAST:event_btnkaliActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=3;
    }//GEN-LAST:event_btntambahActionPerformed

    private void depanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depanbtnActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1:
                angka2 = Double.parseDouble(String.valueOf(display.getText()));
                jumlah = angka1 / angka2;
                angka = Double.toString(jumlah);
            break;
             case 2:
                angka2 = Double.parseDouble(String.valueOf(display.getText()));
                jumlah = angka1 * angka2;
                angka = Double.toString(jumlah);
            break;
             case 3:
                angka2 = Double.parseDouble(String.valueOf(display.getText()));
                jumlah = angka1 + angka2;
                angka = Double.toString(jumlah);
            break;
             case 4:
                angka2 = Double.parseDouble(String.valueOf(display.getText()));
                jumlah = angka1 - angka2;
                angka = Double.toString(jumlah);
            break;
            case 5:
                angka2 = Double.parseDouble(String.valueOf(display.getText()));
                jumlah = angka1 % angka2;
                angka = Double.toString(jumlah);
            break;
            
        }
        display.setText(angka);
    }//GEN-LAST:event_depanbtnActionPerformed

    private void btnmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmin1ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        display.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkomaActionPerformed
        // TODO add your handling code here:
         angka += ".";
        display.setText(angka);
    }//GEN-LAST:event_btnkomaActionPerformed

    private void btnpangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpangkatActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        angka="";         
                jumlah = angka1 * angka1;
                angka = Double.toString(jumlah);
                display.setText(angka);
    }//GEN-LAST:event_btnpangkatActionPerformed

    private void btnpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersenActionPerformed
        angka1=Double.parseDouble(angka);
       angka="";
       jumlah = angka1 / 100;
                angka = Double.toString(jumlah);  
                display.setText(angka);
    }//GEN-LAST:event_btnpersenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("%");
        angka="";
        pilih=5;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        angka="";
        jumlah = Math.sqrt(angka1);
        angka = Double.toString(jumlah);
        display.setText(angka);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        angka="";
        jumlah = Math.sin(Math.toRadians(angka1));
          angka = Double.toString(jumlah);
          display.setText(angka); 

    }//GEN-LAST:event_btnsinActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        angka="";
                jumlah = Math.cos(Math.toRadians(angka1));
         angka = Double.toString(jumlah);
         display.setText(angka); 
    }//GEN-LAST:event_btncosActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        angka="";
        jumlah = Math.tan(Math.toRadians(angka1));
         angka = Double.toString(jumlah);
         display.setText(angka); 
    }//GEN-LAST:event_btntanActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        angka="";
         jumlah = Math.log10(angka1);
         angka = Double.toString(jumlah);
         display.setText(angka);
    }//GEN-LAST:event_btnlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorEa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorEa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorEa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorEa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorEa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bil0;
    private javax.swing.JButton bil1;
    private javax.swing.JButton bil2;
    private javax.swing.JButton bil3;
    private javax.swing.JButton bil4;
    private javax.swing.JButton bil5;
    private javax.swing.JButton bil6;
    private javax.swing.JButton bil7;
    private javax.swing.JButton bil8;
    private javax.swing.JButton bil9;
    private javax.swing.JButton btnbagi;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnkoma;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmin1;
    private javax.swing.JButton btnpangkat;
    private javax.swing.JButton btnpersen;
    private javax.swing.ButtonGroup btnpil;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntan;
    private javax.swing.JButton depanbtn;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
